import React from "react";
import { Check } from "lucide-react";
import { RARITIES, WEAPONS, ARMORS, statsText } from "@/lib/atlasLoot";
import { ACCESSORIES, getBonuses } from "@/lib/atlasSkills";
import { OFFENSIVE_STAT } from "@/lib/atlasSkillDesign";
import { CLASS_WEAPONS } from "@/lib/atlasWeapons";
import { DICE_GROUPS } from "@/lib/atlasDiceSystem";
import { weaponDisplayData } from "@/lib/atlasWeaponInstances";

const STAT_LABELS = { attack: "ATK", defense: "DEF", maxHp: "Vida", maxMp: "Energía", crit: "Crít", speed: "Mov", physDef: "Def. Física", magDef: "Def. Mágica" };
function classWeaponStats(w) { if (!w?.stats) return ""; const offLbl = w.offType === "arcane" ? "Poder Arcano" : w.offType === "precision" ? "Precisión" : "ATK"; return Object.entries(w.stats).map(([k, v]) => { const lbl = k === "attack" ? offLbl : (STAT_LABELS[k] || k); return `+${k === "crit" ? Math.round(v * 100) + "%" : v} ${lbl}`; }).join(" · "); }
function statSum(item) { const s = item?.stats || item?.bonus || {}; return { atk: s.attack || s.atk || 0, physDef: s.physDef || s.def || 0, magDef: s.magDef || 0, maxHp: s.maxHp || 0, maxMp: (s.maxMp || 0) + (item?.maxMp || 0), crit: (s.crit || 0) + (item?.crit || 0), speed: s.speed || 0 }; }
function deltaStr(candidate, current) { const a = statSum(candidate), b = statSum(current); const d = { atk: a.atk - b.atk, physDef: a.physDef - b.physDef, magDef: a.magDef - b.magDef, maxHp: a.maxHp - b.maxHp, maxMp: a.maxMp - b.maxMp }; const parts = []; if (d.atk) parts.push(`${d.atk > 0 ? "+" : ""}${d.atk} ofensiva`); if (d.physDef) parts.push(`${d.physDef > 0 ? "+" : ""}${d.physDef} Def. Física`); if (d.magDef) parts.push(`${d.magDef > 0 ? "+" : ""}${d.magDef} Def. Mágica`); if (d.maxHp) parts.push(`${d.maxHp > 0 ? "+" : ""}${d.maxHp} Vida`); if (d.maxMp) parts.push(`${d.maxMp > 0 ? "+" : ""}${d.maxMp} Energía`); if (!parts.length) return "Sin cambios vs actual"; return parts.join(" · ") + " vs actual"; }
function Slot({ label, name, rarity, refItem, onUnequip, extra, statsLine }) { const rcolor = RARITIES[rarity]?.color; return (<div className="rounded-xl border border-slate-700 bg-slate-800/50 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-400 mb-1">{label}</p>{name ? (<div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="text-sm font-medium truncate" style={{ color: rcolor }}>{name}</p><p className="text-[11px] text-slate-400">{statsLine ?? statsText(refItem)}{refItem?.passive ? ` · ${refItem.passive.desc}` : ""}</p>{extra && <p className="text-[11px] text-fuchsia-300 mt-0.5">{extra}</p>}</div><button onClick={onUnequip} className="text-[11px] rounded-lg bg-slate-700 hover:bg-slate-600 px-2.5 py-1.5 text-slate-200 whitespace-nowrap">Quitar</button></div>) : <p className="text-sm text-slate-500 italic">Vacío</p>}</div>); }
function InvRow({ entry, equipped, currentRef, onEquip }) { const rcolor = RARITIES[entry.rarity]?.color; return (<div className="rounded-lg border border-slate-700 bg-slate-800/40 px-3 py-2"><div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="text-sm font-medium truncate" style={{ color: rcolor }}>{entry.name}</p><p className="text-[11px] text-slate-400">{statsText(entry.ref)}{entry.ref?.passive ? ` · ${entry.ref.passive.desc}` : ""}</p>{!equipped && currentRef && <p className="text-[10px] text-sky-300 mt-0.5">{deltaStr(entry.ref, currentRef)}</p>}</div><div className="flex items-center gap-1.5 shrink-0">{equipped ? <span className="text-[11px] text-emerald-300 flex items-center gap-1"><Check className="w-3 h-3" /> Equipado</span> : <button onClick={onEquip} className="text-[11px] rounded-lg bg-sky-700 hover:bg-sky-600 px-2.5 py-1.5 text-white">Equipar</button>}</div></div></div>); }
function ClassWeaponRow({ id, equipped, onEquip, onSell }) { const w = CLASS_WEAPONS[id]; if (!w) return null; const rcolor = RARITIES[w.rarity]?.color; const dg = DICE_GROUPS[w.ability.diceGroup]; return (<div className={`rounded-lg border px-3 py-2 ${equipped ? "border-emerald-600/60 bg-emerald-950/20" : "border-slate-700 bg-slate-800/40"}`}><div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="text-sm font-medium truncate" style={{ color: rcolor }}>{w.name} <span className="text-[10px] text-slate-400 font-normal">· {w.rarity}</span></p><p className="text-[11px] text-slate-400">{classWeaponStats(w)} · {w.desc}</p><p className="text-[11px] text-fuchsia-200 mt-0.5">⚔ {w.ability.name} <span className="text-slate-500">· {w.ability.cost} energía</span>{dg ? <span className="text-sky-400"> · 🎲 {dg.label}</span> : null}</p><p className="text-[10px] text-slate-500 mt-0.5">{w.ability.desc}</p></div><div className="flex flex-col gap-1 shrink-0">{equipped ? <span className="text-[11px] text-emerald-300 flex items-center gap-1"><Check className="w-3 h-3" /> Equipada</span> : <button onClick={() => onEquip(id)} className="text-[11px] rounded-lg bg-sky-700 hover:bg-sky-600 px-2.5 py-1.5 text-white">Equipar</button>}{!w.relic && w.sell > 0 ? <button onClick={() => onSell(id)} className="text-[11px] rounded-lg bg-amber-700 hover:bg-amber-600 px-2.5 py-1.5 text-white">{w.sell} oro</button> : <span className="text-[10px] text-amber-300">Reliquia</span>}</div></div></div>); }
function entryFor(kind, id) { const ref = kind === "weapon" ? WEAPONS[id] : kind === "armor" ? ARMORS[id] : ACCESSORIES[id]; if (!ref) return null; return { id, kind, name: ref.name, rarity: ref.rarity, ref }; }

export default function HubEquipment({ player, onEquipWeapon, onEquipArmor, onEquipAccessory, onEquipClassWeapon, onSellClassWeapon }) {
  const bonus = getBonuses(player);
  const offStat = OFFENSIVE_STAT[player.class] || OFFENSIVE_STAT.Guerrero;
  const cw = player.classWeapon ? CLASS_WEAPONS[player.classWeapon] : null;
  const lootEquipped = player.weapon ? weaponDisplayData(player, player.weapon) : null;
  const aRef = player.armor ? ARMORS[player.armor] : null;
  const accRef = player.accessory ? ACCESSORIES[player.accessory] : null;
  const cwInv = player.classWeaponInventory || [];
  const wInv = (player.weaponInventory || []).map(raw => { const uid = typeof raw === "string" ? raw : raw?.uid; const d = weaponDisplayData(player, uid); return d ? { id: d.defId, kind: "weapon", name: d.name, rarity: d.rarity, ref: d, uid } : null; }).filter(Boolean);
  const aInv = (player.armorInventory || []).map(id => entryFor("armor", id)).filter(Boolean);
  const accInv = (player.accessoryInventory || []).map(id => entryFor("accessory", id)).filter(Boolean);
  return (
    <div className="p-4 space-y-4 max-w-2xl mx-auto">
      <div><h3 className="text-xs uppercase tracking-widest text-slate-400 mb-2">Equipado</h3><div className="space-y-2"><Slot label="Arma" name={cw?.name || lootEquipped?.name} rarity={cw?.rarity || lootEquipped?.rarity} refItem={cw || lootEquipped} statsLine={cw ? classWeaponStats(cw) : null} extra={cw ? `⚔ ${cw.ability.name} · ${cw.ability.cost} energía` : lootEquipped?.quality ? `✦ ${lootEquipped.quality}` : null} onUnequip={() => cw ? onEquipClassWeapon(player.classWeapon) : onEquipWeapon(player.weapon)} /><Slot label="Armadura" name={aRef?.name} rarity={aRef?.rarity} refItem={aRef} onUnequip={() => onEquipArmor(player.armor)} /><Slot label="Accesorio" name={accRef?.name} rarity={accRef?.rarity} refItem={accRef} onUnequip={() => onEquipAccessory(player.accessory)} /></div></div>
      <div className="rounded-lg border border-slate-700 bg-slate-800/40 px-3 py-2 text-[11px] text-slate-300">Bonificaciones de equipo: <span className="text-emerald-300">{[bonus.atk && `+${bonus.atk} ${offStat.short}`, bonus.def && `+${bonus.def} Def. Física`, bonus.magDef && `+${bonus.magDef} Def. Mágica`, bonus.maxHp && `+${bonus.maxHp} Vida`, bonus.maxMp && `+${bonus.maxMp} Energía`, bonus.crit && `+${Math.round(bonus.crit * 100)}% crít`, bonus.speed && `+${bonus.speed} mov`].filter(Boolean).join(" · ") || "Ninguna"}</span></div>
      {cwInv.length > 0 && (<div><h3 className="text-xs uppercase tracking-widest text-amber-400 mb-1.5">Armas de clase</h3><div className="space-y-1.5">{cwInv.map(id => <ClassWeaponRow key={id} id={id} equipped={player.classWeapon === id} onEquip={onEquipClassWeapon} onSell={onSellClassWeapon} />)}</div></div>)}
      {wInv.length > 0 && (<div><h3 className="text-xs uppercase tracking-widest text-slate-400 mb-1.5">Armas (botín)</h3><div className="space-y-1.5">{wInv.map(e => <InvRow key={e.uid} entry={e} equipped={player.weapon === e.uid} currentRef={null} onEquip={() => onEquipWeapon(e.uid)} />)}</div></div>)}
      {aInv.length > 0 && (<div><h3 className="text-xs uppercase tracking-widest text-slate-400 mb-1.5">Armaduras</h3><div className="space-y-1.5">{aInv.map(e => <InvRow key={e.id} entry={e} equipped={player.armor === e.id} currentRef={aRef} onEquip={() => onEquipArmor(e.id)} />)}</div></div>)}
      {accInv.length > 0 && (<div><h3 className="text-xs uppercase tracking-widest text-slate-400 mb-1.5">Accesorios</h3><div className="space-y-1.5">{accInv.map(e => <InvRow key={e.id} entry={e} equipped={player.accessory === e.id} currentRef={accRef} onEquip={() => onEquipAccessory(e.id)} />)}</div></div>)}
      {cwInv.length === 0 && wInv.length === 0 && aInv.length === 0 && accInv.length === 0 && (<p className="text-sm text-slate-500 italic">Sin equipo en reserva. Explora y derrota enemigos para encontrar botín.</p>)}
      <p className="text-[11px] text-slate-500 leading-snug">Equipa tu mejor equipo aquí. Para vender objetos, acude a un comerciante en su tienda.</p>
    </div>
  );
}