import humanoRig from "@/data/atlasHeroModular/rigs/humano_rig_v1.json";
import elfoRig from "@/data/atlasHeroModular/rigs/elfo_rig_v1.json";
import enanoRig from "@/data/atlasHeroModular/rigs/enano_rig_v1.json";
import partCatalog from "@/data/atlasHeroModular/part_catalog_core.json";
import layerProfiles from "@/data/atlasHeroModular/layer_profiles.json";
import initialLoadouts from "@/data/atlasHeroModular/initial_loadouts.json";
import appearanceProfiles from "@/data/atlasHeroModular/appearance_profiles.json";
import archetypeProps from "@/data/atlasHeroModular/archetype_props.json";
import phase6Registry from "@/data/atlasHeroModular/phase6_universal_clips.json";
import phase7Registry from "@/data/atlasHeroModular/phase7_weapon_clips.json";
import phase7Families from "@/data/atlasHeroModular/phase7_weapon_family_catalog.json";
import phase7Assignments from "@/data/atlasHeroModular/phase7_weapon_assignments.json";
import phase7QualityProfiles from "@/data/atlasHeroModular/phase7_quality_profiles.json";
import phase7ProjectileProfiles from "@/data/atlasHeroModular/phase7_projectile_profiles.json";
import phase7AbilityBindings from "@/data/atlasHeroModular/phase7_ability_bindings.json";
import phase8Catalog from "@/data/atlasHeroModular/phase8_equipment_visual_catalog.json";
import phase8FallbackRules from "@/data/atlasHeroModular/phase8_fallback_rules.json";
import phase8RarityRules from "@/data/atlasHeroModular/phase8_rarity_visual_rules.json";
import phase8StageRules from "@/data/atlasHeroModular/phase8_stage_progression_rules.json";
import phase8Materials from "@/data/atlasHeroModular/phase8_regional_material_library.json";
import assetGateStatus from "@/data/atlasHeroModular/asset_gate_status.json";

export const HERO_RIG_SOURCE = Object.freeze({ humano: humanoRig, elfo: elfoRig, enano: enanoRig });
export const HERO_PART_CATALOG = partCatalog;
export const HERO_LAYER_PROFILES = layerProfiles;
export const HERO_INITIAL_LOADOUTS = initialLoadouts;
export const HERO_APPEARANCE_PROFILES = appearanceProfiles;
export const HERO_ARCHETYPE_PROPS = archetypeProps;
export const HERO_UNIVERSAL_CLIPS = Object.freeze(phase6Registry.clips || {});
export const HERO_WEAPON_CLIPS = Object.freeze(phase7Registry.clips || {});
export const HERO_WEAPON_FAMILY_CATALOG = phase7Families;
export const HERO_WEAPON_ASSIGNMENTS = phase7Assignments;
export const HERO_WEAPON_QUALITY_PROFILES = phase7QualityProfiles;
export const HERO_PROJECTILE_PROFILES = phase7ProjectileProfiles;
export const HERO_ABILITY_ANIMATION_BINDINGS = phase7AbilityBindings;
export const HERO_EQUIPMENT_VISUAL_CATALOG = phase8Catalog;
export const HERO_EQUIPMENT_FALLBACK_RULES = phase8FallbackRules;
export const HERO_EQUIPMENT_RARITY_RULES = phase8RarityRules;
export const HERO_EQUIPMENT_STAGE_RULES = phase8StageRules;
export const HERO_REGIONAL_MATERIAL_LIBRARY = phase8Materials;
export const HERO_ASSET_GATE_STATUS = assetGateStatus;
