import { registerPlugin } from '@capacitor/core'
const API=registerPlugin('AtlasQa')
const $=s=>document.querySelector(s)
const els={importStatus:$('#importStatus'),importMsg:$('#importMsg'),importPct:$('#importPct'),importBar:$('#importBar'),suggested:$('#suggested'),suggestedName:$('#suggestedName'),suggestedMeta:$('#suggestedMeta'),runSuggested:$('#runSuggested'),favSuggested:$('#favSuggested'),empty:$('#empty'),importBtn:$('#importBtn'),refreshBtn:$('#refreshBtn'),studioBtn:$('#studioBtn'),libraryMeta:$('#libraryMeta'),selectAll:$('#selectAll'),batch:$('#batch'),batchText:$('#batchText'),clearSel:$('#clearSel'),deleteSel:$('#deleteSel'),versions:$('#versions')}
const selected=new Set();let versions=[];let poll=null
const css=document.createElement('style');css.textContent=`*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#07110c;color:#edf7f0;font-family:system-ui,-apple-system,sans-serif}body{padding:22px 14px 34px}main{width:min(620px,100%);margin:auto}header{text-align:center;padding:12px 0 18px}.mark{font-size:11px;letter-spacing:.46em;color:#9eb0a6;font-weight:800}h1{font-size:32px;margin:5px 0 1px}h2{font-size:20px;margin:7px 0 8px;word-break:break-word}.sub,.muted,.hint,small{color:#9eb0a6}.sub{margin:0}.card{background:#0d1c14;border:1px solid #1f3d2c;border-radius:18px;padding:16px;margin:10px 0;box-shadow:0 8px 26px #0003}.eyebrow{font-size:10px;letter-spacing:.15em;color:#7dd3a6;font-weight:900}.row{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px}button{border:0;border-radius:12px;padding:12px 13px;font-weight:800;font-size:13px}.primary{background:#ccebd8;color:#07110c}.ghost{background:#183124;color:#edf7f0}.bar{height:7px;background:#173126;border-radius:99px;overflow:hidden;margin:12px 0}.bar i{display:block;height:100%;width:0;background:#7dd3a6;transition:width .25s}.hint{font-size:12px;line-height:1.4;margin-bottom:0}.studioCard{border-color:#315b43}.studioBtn{width:100%;margin-top:12px}.libraryHead{display:flex;align-items:center;justify-content:space-between;padding:17px 4px 7px}.linkBtn{background:transparent;color:#9fdab8;padding:8px}.batch{position:sticky;top:8px;z-index:4;background:#173126;border:1px solid #2e5b43;border-radius:14px;padding:10px 12px;margin:8px 0;display:flex;align-items:center;justify-content:space-between;box-shadow:0 8px 22px #0007}.batch>div{display:flex;gap:6px}.mini{padding:8px 10px;background:#294a38;color:#edf7f0;border-radius:9px}.danger{background:#5b2e2b;color:#ffd7d3}.version{background:#0b1811;border:1px solid #1b3426;border-radius:16px;padding:13px;margin:8px 0}.vtop{display:grid;grid-template-columns:34px 1fr auto;gap:8px;align-items:start}.check{width:22px;height:22px;margin-top:2px;accent-color:#7dd3a6}.vname{font-size:16px;font-weight:850;line-height:1.25}.badges{font-size:10px;color:#7dd3a6;font-weight:850;margin-top:3px}.meta{font-size:11px;color:#9eb0a6;margin-top:5px;line-height:1.35;word-break:break-word}.star{background:transparent;color:#d9e9df;font-size:21px;padding:0 3px;line-height:1}.vrun{width:100%;margin-top:10px;background:#ccebd8;color:#07110c}.notes{font-size:11px;color:#a9bbb0;margin-top:7px;line-height:1.35}footer{text-align:center;color:#63776c;font-size:10px;padding:20px 0 4px}@media(max-width:390px){body{padding:16px 10px 28px}h1{font-size:29px}.actions{grid-template-columns:1fr 1fr}.card{padding:14px}}`;document.head.appendChild(css)
const fmtSize=n=>n>=1073741824?(n/1073741824).toFixed(2)+' GB':n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?Math.round(n/1024)+' KB':n+' B'
const fmtDate=n=>n?new Date(n).toLocaleString():'—'
function render(){const s=versions[0];els.suggested.hidden=!s;els.empty.hidden=!!s;if(s){els.suggestedName.textContent=s.displayName;els.suggestedMeta.textContent=`${fmtSize(s.sizeBytes)} · ${fmtDate(s.importedAt)}\n${s.sourceName||''}`;els.favSuggested.textContent=s.favorite?'★ Favorita':'☆ Fijar';els.runSuggested.onclick=()=>run(s.id);els.favSuggested.onclick=()=>fav(s.id)}const total=versions.reduce((a,v)=>a+(v.sizeBytes||0),0);els.libraryMeta.textContent=`${versions.length} ${versions.length===1?'versión':'versiones'} · ${fmtSize(total)}`;els.versions.innerHTML='';for(const v of versions){const c=document.createElement('article');c.className='version';const checked=selected.has(v.id);c.innerHTML=`<div class="vtop"><input class="check" type="checkbox" ${checked?'checked':''}><div><div class="vname">${v.favorite?'★ ':''}${esc(v.displayName)}</div><div class="badges">${[v.suggested?'SUGERIDA':'',v.lastPlayed?'ÚLTIMA EJECUTADA':''].filter(Boolean).join(' · ')}</div><div class="meta">${fmtSize(v.sizeBytes)} · ${fmtDate(v.importedAt)}<br>${esc(v.sourceName||'')}</div>${v.notes?`<div class="notes">${esc(v.notes)}</div>`:''}</div><button class="star">${v.favorite?'★':'☆'}</button></div><button class="vrun">▶ Ejecutar esta versión</button>`;c.querySelector('.check').onchange=e=>{e.target.checked?selected.add(v.id):selected.delete(v.id);renderBatch()};c.querySelector('.star').onclick=()=>fav(v.id);c.querySelector('.vrun').onclick=()=>run(v.id);els.versions.appendChild(c)}renderBatch()}
function renderBatch(){els.batch.hidden=selected.size===0;els.batchText.textContent=`${selected.size} seleccionada${selected.size===1?'':'s'}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function refresh(){try{const x=await API.listVersions();versions=x.versions||[];for(const id of [...selected])if(!versions.some(v=>v.id===id))selected.delete(id);render();await importStatus()}catch(e){alert('Atlas QA no pudo leer las versiones: '+(e.message||e))}}
async function fav(id){await API.toggleFavorite({id});await refresh()}
async function launchStudio(){try{const r=await API.launchStudio();if(!r?.url)throw new Error('Studio no devolvió URL');window.location.href=r.url}catch(e){alert('No pude abrir Character Studio: '+(e.message||e))}}
async function run(id){try{const x=await API.launchVersion({id});location.assign(x.url)}catch(e){alert(e.message||'No pude ejecutar Atlas')}}
async function importStatus(){try{const s=await API.getImportStatus();if(s.state==='working'){els.importStatus.hidden=false;els.importMsg.textContent=s.message||'Importando…';const p=Math.max(0,Math.min(100,s.progress||0));els.importPct.textContent=p+'%';els.importBar.style.width=p+'%';startPoll()}else{els.importStatus.hidden=true;if(poll){clearInterval(poll);poll=null}}}catch{els.importStatus.hidden=true}}
function startPoll(){if(poll)return;poll=setInterval(async()=>{await importStatus();const s=await API.getImportStatus();if(s.state!=='working'){clearInterval(poll);poll=null;await refresh()}},900)}
els.importBtn.onclick=async()=>{try{const r=await API.pickImport();if((r.count||0)>0){els.importStatus.hidden=false;startPoll()}}catch(e){alert('No pude abrir el selector: '+(e.message||e))}}
els.refreshBtn.onclick=refresh;els.studioBtn.onclick=launchStudio;els.selectAll.onclick=()=>{if(versions.length&&selected.size===versions.length)selected.clear();else versions.forEach(v=>selected.add(v.id));render()};els.clearSel.onclick=()=>{selected.clear();render()};els.deleteSel.onclick=async()=>{if(!selected.size)return;if(!confirm(`¿Borrar ${selected.size} versión${selected.size===1?'':'es'}?`))return;await API.deleteVersions({ids:[...selected]});selected.clear();await refresh()}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});refresh()
